### ISSUE TITLE
你好,为什么在addDanmu中的  danmaku.priority = 0;指定1时会导致行数失效,view折叠的情况

### ISSUE THREAD

**Issue by est7** [cock-tail/DanmuDemo#1]
在代码中找priority属性没找到这个属性的使用位置....不知道怎么改...抱拳

**Comment by wangpeiyuan** [comment]
@est7 priority这个属性是第三方库DanmakuFlameMaster里面使用的，具体的话，你可能需要去看一下源码

**Comment by est7** [comment]
@wangpeiyuan 谢谢了,在issuse里itiao给了解决办法

首选要知道一屏最多几行弹幕，发送第一批x条弹幕(x=行数)

当前弹幕时间 + 一定增量时间，用DanmakuUtils.willHitInDuration检查第一行弹幕与当前要插入弹幕是否会碰撞，会碰撞则再增加一定时间再检查，不会碰撞则确定当前弹幕出现的time，如此循环直到插完第二批x条弹幕(x=行数)
后面剩余的弹幕同样处理。
