### ISSUE TITLE
提一个关于弹幕速度的问题

### ISSUE THREAD

**Issue by luoyiqi** [cock-tail/DanmuDemo#3]
Danmu danmu6 = new Danmu(0, 3, "Comment", R.mipmap.wat, "这还是一条弹幕啦啦啦");
//可以正常速度播放
Danmu danmu6 = new Danmu(0, 3, "Comment", R.mipmap.wat, "这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦这还是一条弹幕啦啦啦");
//不可以可以正常速度播放了，速度会超快
当text过长的时候，该条弹幕会十分快速的闪过去。我尝试去修改，但还是没做出允许播放的效果，无论text是长还是短的时候。
第一次提issues，希望作者给个回复。（如何控制弹幕速度）

**Comment by wangpeiyuan** [comment]
这个问题原因在于 [DanmakuFlameMaster](https://github.com/Bilibili/DanmakuFlameMaster) 只提供调整整体弹幕的速度，并不提供每一天弹幕使用不同速度，你可以看一下 DanmakuFlameMaster 这个库的使用
